### ISSUE TITLE
SMB msgrate benchmark hangs

### ISSUE THREAD

**Issue by BrodyWilliams** [openucx/openhpca#18]
I encountered an issue with the SMB msgrate benchmark when testing using the long version of the benchmark run. It seems that the execution hangs early on and the job is eventually killed by slurm when the time limit is reached.

Looking at the script generated by the Go infrastructure, one problem is likely to be that the benchmark specific parameters are not currently passed in. However, something else may also be going on. Adding the correct flags did not fix the issue in my case. Execution seems to be hanging at, or about, MPI_thread_init(), for yet undiscovered reasons.

**Comment by gvallee** [comment]
As a note, I may just have overlooked the management of parameters for that benchmarks. Everything is there to manage them but i would not be surprised if i overlook the details for that benchmark.
