### ISSUE TITLE
error at the end of execution

### ISSUE THREAD

**Issue by gvallee** [openucx/openhpca#3]
I see the following error sometimes after all jobs are done. Unclear at this point if a job failed or if the compilation of results is just facing a problem:
```
ERROR: unable to display results: undefined data
```

**Comment by BrodyWilliams** [comment]
@gvallee I am seeing this error now as well. I also get other variants of "Error: Unable to display results: ...". In my case, it seems the overlap runs are failing. I am not sure if this is the same problem you are encountering or a configuration issue/other problem on my end. I have the output from stderr uploaded [here](https://github.com/BrodyWilliams/openhpca/tree/debugging/debug). I will take a closer look when I get a chance.

**Comment by BrodyWilliams** [comment]
> > @gvallee I am seeing this error now as well. I also get other variants of "Error: Unable to display results: ...". In my case, it seems the overlap runs are failing. I am not sure if this is the same problem you are encountering or a configuration issue/other problem on my end. I have the output from stderr uploaded [here](https://github.com/BrodyWilliams/openhpca/tree/debugging/debug). I will take a closer look when I get a chance.
> 
> It seems to be different, in your case, the MPI implementation crashed. I will have to spend time going through the logs and try to understand what is going on. I do not think it is straightforward but i may have missed something. And thanks for sharing the details, it is definitely helpful.

I think I may have found something. If I'm not mistaken, it seems, at least for the time driven model with default sizes, that n_elts is growing beyond params->max_elts for s_buf/r_buf in the loop with get_coll_config_info().  In turn, this causes a segmentation fault on the actual MPI call. I will verify tomorrow.

**Comment by BrodyWilliams** [comment]
@gvallee
The above was in fact causing issues on my end. I addressed the problem by forcing the user to increase the max_nelts size. Alternatively, it might also be possible to fix dynamically, but that seems like it might affect the calculation process. There also seems to be a problem with igatherv/iallgatherv where the r_counts does not include the elements from the current process, but the MPI call uniformly sources n_elts from all processes.

The code here #17 is working for me for the default tests (after increasing the max_nelts), but I have not tried the long versions of the run. I will let you review and edit.

**Comment by gvallee** [comment]
It is all confirmed that the error message happens when a test fails, currently when the overlap benchmarks need customization. PR#24 ensures that the value of the environment is correctly passed down to the overlap benchmarks; update the documentation accordingly and clarify the error messages.
