### ISSUE TITLE
Unable to complete overlap NBC's with Time-Driven Execution -- "Cannot Further increase n_elts"

### ISSUE THREAD

**Issue by BTMichalowicz** [openucx/openhpca#34]
I'm trying to run some experiments with the time-driven execution model inside the overlap_XYZ collectives, and for all of them, regardless of MPI library, I get the following error (see attached):

![image](https://user-images.githubusercontent.com/27008062/190015987-2280d913-c51b-4595-b0bf-e5869d47b88f.png)

This error occurs no matter how high I set `OPENHPCA_OVERLAP_MAX_NUM_ELTS`, though for some reason, I'm able to get per-message-size latencies if I turn on the calibration feature (not documented, see overlap.h for `OPENHPCA_OVERLAP_CALIBRATION`). Because of this, I'm not able to see the final output generated for the Time-Driven model (work injected, latency, %-overlap, etc.)

In this particular case, I'm running overlap_igather with the following command: `mpirun -np <ntasks> --hostfile hostfile /path/to/overlap_igather` after exporting `OPENHPCA_OVERLAP_MAX_NUM_ELTS`

What can I do to fix this?
Thank you!

**Comment by BrodyWilliams** [comment]
Hi Benjamin - If you have not already done so, could you try running with

"mpirun -np <ntasks> -x OPENHPCA_OVERLAP_MAX_NUM_ELTS=<some_number> --hostfile hostfile /path/to/overlap_igather" 

(or the equivalent for non-OpenMPI implementations) to eliminate the possibility that the environment variable is not being properly set on each node?

**Comment by BTMichalowicz** [comment]
Hi Brody. Sorry for the delay. I just got to run the command, and the error still occurs.

**Comment by gvallee** [comment]
@BTMichalowicz  This is most certainly because the default parameters are out-of-range for the scale at which you are running. Could you please tell us how many ranks, nodes and process per nodes you are using when you face this issue?

**Comment by BTMichalowicz** [comment]
Hi @gvallee, 

Thanks for the clarification! I've run these anywhere from 2 nodes/1 PPN to 3/4 nodes and 40 PPN. The only error I really change is `OPENHPCA_OVERLAP_MAX_NUM_ELTS` with everything else being left at their default values (min number of elements, overlap calibration turned off, number of iterations set to their default values, etc.). What scale _should_ I be running these at with the default settings?

An interesting thing I found a couple of weeks ago was that setting `OPENHPCA_OVERLAP_CALIBRATION` to 1 allows me to see the latency for each message size before crashing with the same error I mentioned above.

**Comment by gvallee** [comment]
@BTMichalowicz thanks for the details, i will have to look at it more closely, it should work with 12 nodes for sure, my testing are often based on 10 nodes, 40 ppn. I did all these things long enough ago that i do not remember all the details. Sorry.

**Comment by BTMichalowicz** [comment]
> @BTMichalowicz thanks for the details, i will have to look at it more closely, it should work with 12 nodes for sure, my testing are often based on 10 nodes, 40 ppn. I did all these things long enough ago that i do not remember all the details. Sorry.

No worries! I'll mess around with some other parameters and see what might help, and I'll keep this issue updated with anything I find.

**Comment by BTMichalowicz** [comment]
Update @gvallee @BrodyWilliams -- I didn't think to  The "default" macro is currently set to 500 (microseconds I'm assuming) by default, so attempting any run without changing it accordingly will cause an initial loop calling `CHECK_N_ELTS` to keep going until e.g. igather (or any other collective) crashes -- the avg_wait time for another smaller than, e.g 32 Nodes, full subscription on 40-core machines would probably take less than that 500 microseconds.

**Comment by gvallee** [comment]
@BTMichalowicz Thanks for your patience and I believe you are correct. As a manner of fact, i just pushed code to generate a report that includes details about errors while running OpenHPCA and i also just added the average wait time to the error message so i can see what the execution looks looks on your system. This is something i wanted to do for a while but never took the time to finalize, sorry about that (issue #20).

So if you do not mind generating that report, could you please send it to me to geoffroy .at. nvidia.com? But please not that details about the platform are including in the report so do not send me that report if details cannot be publicly shared.

To generate the report, get the `main` branch, re-compile everything, re-run the suite and then execute `./tools/cmd/openhpc_report/openhpca_report`. The path to the report will be displayed when running the tool. If we can confirm the problem, we can then see how to quickly have you up and running but also how to address that problem as hardware gets better.

Sorry to ask so much from you but i really would like to find a good long-term solution. I hope you do not mind too much going through that process.

**Comment by BTMichalowicz** [comment]
Hi @gvallee 

Sorry for the delayed response. I'd be happy to create the report and everything. To clarify, do you want me to run things without the modified cutoff before generating the report? Or should I make guesses a priori w.r.t the cutoff time?

**Comment by gvallee** [comment]
Hi,

Without the modified cutoff at first would be best for me.

Thanks

**Comment by gvallee** [comment]
@BTMichalowicz now we have switched to a new version of the `go_hpc_jobmgr` package, could you please update and give it another try?

**Comment by BTMichalowicz** [comment]
Hi @gvallee, 

Not sure why, but the scripts being generated from the use with MVAPICH2 still result in it being "recognized" as mpich. I'll do some debugging when I get the chance.

**Comment by gvallee** [comment]
@BTMichalowicz i just realized that some of the other package I have also rely on `job_mgr_HPC` but I did not update those. I will do so asap.

**Comment by BTMichalowicz** [comment]
Ah, I see. Thank you for figuring that out!

**Comment by gvallee** [comment]
@BTMichalowicz I updated all the dependencies. Hopefully i did not miss one and we will never have to touch it again, MVAPICH will have native support in all packages. Sorry about missing it in the first place; i did not touch these packages in a while.
Could you please give it another try?

**Comment by BTMichalowicz** [comment]
Hi @gvallee! Sorry for the delay on this. Still no luck for some reason. I've done all the git-pull's as needed to get both the OpenHPCA suite and `go_hpc_job_mgr` library. Are there any environment variables I'm missing to trigger the MVAPICH2-based path?

**Comment by gvallee** [comment]
@BTMichalowicz It should not depend on any environment variable. Let's sync over email to see if i can use your stack on the system we can both access. Could you please send me an email with the path? Thanks

**Comment by BTMichalowicz** [comment]
Closing this issue as everything discussed here and through email has been resolved :)
